server:
  port: 8080
  use-forward-headers: true
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5434/pedidos"
    username: admin
    password: admin
  rabbitmq:
    host: localhost
    port: 5673
    username: guest
    password: guest
  jpa:
    hibernate:
      use-new-id-generator-mappings: true